Name: deploy the tic-tac-toe app to ssh server
on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm test   
      
      - name: build the app
        run: npm run build
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Wait for Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vk2615/tic-tac-toe:latest
      - name: trivy security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vk2615/tic-tac-toe:latest
      - name: notify deployment start
        uses: slackapi/slack-github-action@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "Deployment to production started for tic-tac-toe app."

      - name: deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_SERVER_KEY }}
          script: |
            docker pull vk2615/tic-tac-toe:latest
            docker stop tic-tac-toe || true
            docker rm tic-tac-toe || true
            docker run -d -p 3000:80 --name tic-tac-toe vk2615/tic-tac-toe:latest  

      - name: notify deployment success
        if: success()
        uses: slackapi/slack-github-action@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "Deployment to production succeeded for tic-tac-toe app."

      - name: notify deployment failure
        if: failure()
        uses: slackapi/slack-github-action@v2
        with: 
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "Deployment to production failed for tic-tac-toe app."